name: 'git-restore-mtime'
description: "Restore file's modified time (timestamp) based on git commits"
author: 'Pixelcop Research, Inc.'
branding:
  icon: 'clock'
  color: 'orange'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        $GITHUB_ACTION_PATH/git-restore-mtime --commit-time
